import { uid } from "uid";

const packingList = [
  {
    category: "Clothes",
    name: "T-Shirt",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Sweater",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Rain Jacket",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Pants",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Shorts",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Swimsuit",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Sneakers",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Hiking Boots",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Flip Flops",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Accessories",
    name: "Towel",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Accessories",
    name: "Sunglasses",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Accessories",
    name: "Hat",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Sunscreen",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Toothbrush",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Toothpaste",
    number: "",
    checked: false,
    id: uid(),
  },
];

export default packingList;
