import { uid } from "uid";

const packingList = [
  {
    category: "Clothes",
    name: "T-Shirt",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Sweater",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Jacket",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Pants",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Shorts",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Skirt",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Dress",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Swimsuit",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Sneakers",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Hiking Boots",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Flip Flops",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Socks",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Clothes",
    name: "Underwear",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Accessories",
    name: "Towel",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Accessories",
    name: "Sunglasses",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Accessories",
    name: "Hat",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Accessories",
    name: "Jewellry",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Sunscreen",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Toothbrush",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Toothpaste",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Shampoo",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Aftersun",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Razor",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Cosmetics",
    name: "Hairbrush",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Technology",
    name: "Phone",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Technology",
    name: "Phone Charger",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Technology",
    name: "Camera",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Technology",
    name: "Laptop",
    number: "",
    checked: false,
    id: uid(),
  },
  {
    category: "Technology",
    name: "Headphones",
    number: "",
    checked: false,
    id: uid(),
  },
];

export default packingList;
