import { uid } from "uid";

const trips = [
  {
    slug: "jordan",
    name: "Jordan",
    startDate: "2025-08-29",
    endDate: "2025-09-07",
    image: "https://source.unsplash.com/llTLNIFEgZ8/640x426",
    geocode: [31.312, 35.939],
    id: uid(),
    expenses: [
      { name: "City Tour", amount: "18.99", date: "2025-08-29", id: uid() },
      { name: "Dinner", amount: "30.00", date: "2025-08-29", id: uid() },
      { name: "Hotel", amount: "45.00", date: "2025-08-29", id: uid() },
      { name: "Falafel", amount: "20.00", date: "2025-08-30", id: uid() },
      { name: "Entry Fee", amount: "12.20", date: "2025-08-30", id: uid() },
      { name: "Massage", amount: "28.50", date: "2025-08-31", id: uid() },
      { name: "Bus Ticket", amount: "4.99", date: "2025-08-31", id: uid() },
      { name: "Bus Ticket", amount: "7.80", date: "2025-09-01", id: uid() },
      {
        name: "Petra at Night",
        amount: "38.00",
        date: "2025-09-01",
        id: uid(),
      },
      { name: "National Park", amount: "10.00", date: "2025-09-02", id: uid() },
      { name: "Homestay", amount: "27.50", date: "2025-09-02", id: uid() },
      { name: "Wadi Rum Tour", amount: "38.90", date: "2025-09-04", id: uid() },
      { name: "Bedouin Camp", amount: "49.00", date: "2025-09-04", id: uid() },
      { name: "Bus Ticket", amount: "4.99", date: "2025-09-05", id: uid() },
      { name: "City Tour", amount: "13.56", date: "2025-09-05", id: uid() },
      {
        name: "Snorkelling Trip",
        amount: "27.70",
        date: "2025-09-06",
        id: uid(),
      },
      { name: "Dinner", amount: "30.00", date: "2025-09-06", id: uid() },
      {
        name: "Taxi to Airport",
        amount: "14.22",
        date: "2025-09-07",
        id: uid(),
      },
      {
        name: "Bus to Dead Sea",
        amount: "5,80",
        date: "2025-08-30",
        id: uid(),
      },
    ],
    packingList: [
      {
        category: "Clothes",
        name: "T-Shirt",
        number: "8",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Sweater",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Jacket",
        number: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Pants",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Shorts",
        number: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Skirt",
        number: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Dress",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Swimsuit",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Sneakers",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Hiking Boots",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Flip Flops",
        number: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Socks",
        number: "7",
        checked: true,
        id: uid(),
      },
      {
        category: "Clothes",
        name: "Underwear",
        number: "7",
        checked: true,
        id: uid(),
      },
      {
        category: "Accessories",
        name: "Towel",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Accessories",
        name: "Sunglasses",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Accessories",
        name: "Hat",
        number: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Accessories",
        name: "Jewellry",
        number: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Cosmetics",
        name: "Sunscreen",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Cosmetics",
        name: "Toothbrush",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Cosmetics",
        name: "Toothpaste",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Cosmetics",
        name: "Shampoo",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Cosmetics",
        name: "Aftersun",
        number: "",
        amount: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Cosmetics",
        name: "Razor",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Cosmetics",
        name: "Hairbrush",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Technology",
        name: "Phone",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Technology",
        name: "Phone Charger",
        number: "1",
        checked: true,
        id: uid(),
      },
      {
        category: "Technology",
        name: "Camera",
        number: "",
        amount: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Technology",
        name: "Laptop",
        number: "",
        amount: "",
        checked: false,
        id: uid(),
      },
      {
        category: "Technology",
        name: "Headphones",
        number: "1",
        checked: true,
        id: uid(),
      },
    ],
    documents: [
      { name: "Passport copy", id: uid() },
      { name: "Boarding pass", id: uid() },
      { name: "Travel insurance", id: uid() },
    ],
  },
];

export default trips;
